/**
 * Git hook installation for asset guards.
 *
 * Reads the asset manifest's declared guards and writes `.git/hooks/pre-commit`
 * (architecture/quality guard checks — rejects bad changes at the only gate
 * every change passes) and `post-commit` (codegraph incremental refresh).
 * Hooks are derived from the manifest; installing is idempotent and the
 * uninstall removes only hooks this tool wrote.
 */
import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Marker embedded in generated hooks so uninstall can identify (and only
 * remove) hooks this tool wrote, never a user's own hook.
 */
const HOOK_MARKER = "# generated by omp asset install-hooks";

/** Build the pre-commit hook script from guard commands. */
export function buildPreCommitScript(
	guardCommands: string[],
	options: { includeDriftCheck?: boolean; driftPaths?: string[] } = {},
): string {
	const checks = guardCommands
		.map(
			cmd => `  echo "  → ${cmd}"\n  if ! (${cmd}); then\n    echo "❌ guard failed: ${cmd}" >&2\n    exit 1\n  fi`,
		)
		.join("\n");
	const driftCheck = options.includeDriftCheck
		? `\n# Description drift check — archDoc references to symbols that vanished.\n# Warning-only: drift is a doc-update reminder, not a hard gate (guards are).\n${buildDriftRun(options.driftPaths ?? [])}`
		: "";
	return `#!/bin/sh
${HOOK_MARKER}
# Asset guard checks — derived from omp.assets.json (guard.trigger=pre-write).
# Rejected changes never enter the repository, regardless of who made them.
set -e
cd "$(git rev-parse --show-toplevel)"
echo "Running asset guards..."
${checks}${driftCheck}
`;
}

/**
 * The drift check reads the declared archDoc paths and nothing else, so when
 * those paths are known it is gated on the commit having staged one of them:
 * a code-only commit would otherwise pay the full scan cost for no signal.
 */
function buildDriftRun(driftPaths: string[]): string {
	const run =
		'echo "Checking description drift..."\nif command -v omp >/dev/null 2>&1; then\n  omp asset check-drift --warn-only || true\nfi';
	if (driftPaths.length === 0) return run;
	return `# Only runs when this commit staged a path under a declared archDoc asset.\nif git diff --cached --name-only --diff-filter=ACMR | grep -qE '${driftPathPattern(driftPaths)}'; then\n  echo "Checking description drift..."\n  if command -v omp >/dev/null 2>&1; then\n    omp asset check-drift --warn-only || true\n  fi\nfi`;
}

/** POSIX ERE matching a staged path under any declared archDoc asset. */
function driftPathPattern(paths: string[]): string {
	return paths.map(p => `^${p.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}(/|$)`).join("|");
}

/** Build the post-commit hook script (codegraph incremental refresh). */
export function buildPostCommitScript(projectRoot: string): string {
	return `#!/bin/sh
${HOOK_MARKER}
# Incremental refresh of the code graph index after each commit.
cd "${projectRoot}" || exit 0
command -v codegraph >/dev/null 2>&1 && codegraph sync -q || true
`;
}

/**
 * Install guard hooks into the repository's `.git/hooks`. Preserves an
 * existing user-written hook by appending to it; idempotent on re-run.
 * Returns the list of hooks written.
 */
export function installGitHooks(
	projectRoot: string,
	guardCommands: string[],
	options: { includeDriftCheck?: boolean; driftPaths?: string[] } = {},
): string[] {
	const hooksDir = gitHooksDir(projectRoot);
	fs.mkdirSync(hooksDir, { recursive: true });

	const preCommit = buildPreCommitScript(guardCommands, options);
	const postCommit = buildPostCommitScript(projectRoot);

	const written: string[] = [];
	if (writeHook(hooksDir, "pre-commit", preCommit)) written.push("pre-commit");
	if (writeHook(hooksDir, "post-commit", postCommit)) written.push("post-commit");
	return written;
}

/** Remove hooks this tool wrote. Returns removed hook names. */
export function uninstallGitHooks(projectRoot: string): string[] {
	const hooksDir = gitHooksDir(projectRoot);
	const removed: string[] = [];
	for (const name of ["pre-commit", "post-commit"] as const) {
		const p = path.join(hooksDir, name);
		const content = readFile(p);
		if (content === null) continue;
		if (!content.includes(HOOK_MARKER)) continue; // user's own hook — leave it
		// Strip the generated block (from the marker onward), preserving any
		// user-written prefix before it. Drop the generated shebang that
		// precedes the marker; if only our own header remains, remove the file.
		const markerIdx = content.indexOf(HOOK_MARKER);
		let userPart = content.slice(0, markerIdx).trimEnd();
		userPart = userPart.replace(/\n*#!.*\n?$/, "").trimEnd();
		if (userPart.length > 0) {
			fs.writeFileSync(p, `${userPart}\n`, { mode: 0o755 });
		} else {
			fs.rmSync(p, { force: true });
		}
		removed.push(name);
	}
	return removed;
}

// ── git dir resolution (supports worktrees, submodules, core.hooksPath) ─────

function gitHooksDir(projectRoot: string): string {
	const gitDir = resolveGitDir(projectRoot);
	const coreConfig = readFile(path.join(gitDir, "config"));
	if (coreConfig) {
		const m = coreConfig.match(/\[core\]\s*hooksPath\s*=\s*(.+)/);
		if (m) return m[1].trim().replace(/^~/, process.env.HOME ?? "~");
	}
	return path.join(gitDir, "hooks");
}

function resolveGitDir(projectRoot: string): string {
	const gitPath = path.join(projectRoot, ".git");
	let stat: fs.Stats;
	try {
		stat = fs.statSync(gitPath);
	} catch {
		throw new Error(`No .git found at ${projectRoot}`);
	}
	if (stat.isDirectory()) return gitPath;
	// Worktree / submodule: `.git` is a file pointing at `gitdir: <path>`.
	const content = fs.readFileSync(gitPath, "utf-8");
	const m = content.match(/^gitdir:\s*(.+)$/m);
	if (m) return m[1].trim();
	throw new Error(`Unrecognized .git at ${gitPath}`);
}

function writeHook(hooksDir: string, name: string, content: string): boolean {
	const p = path.join(hooksDir, name);
	const existing = readFile(p);
	// Preserve any user-written prefix before our marker. Drop the tool's own
	// shebang that precedes the marker (it belongs to the generated block).
	let userPrefix = existing ?? "";
	if (existing?.includes(HOOK_MARKER)) {
		userPrefix = existing.slice(0, existing.indexOf(HOOK_MARKER));
		userPrefix = userPrefix.replace(/\n*#!.*\n?$/, "").trimEnd();
	}
	const body = userPrefix.length > 0 ? `${userPrefix}\n${content}` : content;
	if (existing === body) return false; // already installed with identical content
	fs.writeFileSync(p, body, { mode: 0o755 });
	return true;
}

function readFile(p: string): string | null {
	try {
		return fs.readFileSync(p, "utf-8");
	} catch {
		return null;
	}
}
