import { afterEach, describe, expect, test } from "bun:test";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

import {
	buildPostCommitScript,
	buildPreCommitScript,
	installGitHooks,
	uninstallGitHooks,
} from "../src/asset-anchors/git-hooks";

const tmpDirs: string[] = [];

function makeRepo(): string {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), "git-hooks-"));
	tmpDirs.push(dir);
	fs.mkdirSync(path.join(dir, ".git"));
	fs.mkdirSync(path.join(dir, ".git", "hooks"));
	return dir;
}

afterEach(() => {
	for (const dir of tmpDirs.splice(0)) {
		fs.rmSync(dir, { recursive: true, force: true });
	}
});

describe("buildPreCommitScript", () => {
	test("embeds each guard command and exits non-zero on failure", () => {
		const script = buildPreCommitScript(["test -f arch.json", "test -d src"]);
		expect(script).toContain("test -f arch.json");
		expect(script).toContain("test -d src");
		expect(script).toContain("exit 1");
		expect(script).toContain("# generated by omp asset install-hooks");
	});

	test("runs guards in order and rejects when a guard fails", () => {
		const script = buildPreCommitScript(["false"]);
		const run = Bun.spawnSync(["sh", "-c", script]);
		expect(run.exitCode).not.toBe(0);
	});

	test("passes when all guards succeed", () => {
		const script = buildPreCommitScript(["true"]);
		const run = Bun.spawnSync(["sh", "-c", script]);
		expect(run.exitCode).toBe(0);
	});

	test("embeds the drift check when includeDriftCheck is set", () => {
		const script = buildPreCommitScript(["true"], { includeDriftCheck: true });
		expect(script).toContain("omp asset check-drift --warn-only");
		expect(script).toContain("description drift");
		expect(script).toContain("|| true"); // warning-only, never blocks commit
	});

	test("omits the drift check by default", () => {
		const script = buildPreCommitScript(["true"]);
		expect(script).not.toContain("omp asset check-drift");
	});
});

describe("buildPostCommitScript", () => {
	test("includes the codegraph incremental sync and the marker", () => {
		const script = buildPostCommitScript("/tmp/proj");
		expect(script).toContain("codegraph sync -q");
		expect(script).toContain("/tmp/proj");
		expect(script).toContain("# generated by omp asset install-hooks");
	});
});

describe("installGitHooks / uninstallGitHooks", () => {
	test("writes both hooks with executable bit", () => {
		const repo = makeRepo();
		const written = installGitHooks(repo, ["true"]);
		expect(written).toEqual(["pre-commit", "post-commit"]);

		const preStat = fs.statSync(path.join(repo, ".git", "hooks", "pre-commit"));
		expect(preStat.mode & 0o111).not.toBe(0);
		expect(fs.readFileSync(path.join(repo, ".git", "hooks", "pre-commit"), "utf-8")).toContain(
			"# generated by omp asset install-hooks",
		);
	});

	test("is idempotent — reinstall does not duplicate hooks", () => {
		const repo = makeRepo();
		installGitHooks(repo, ["true"]);
		const written2 = installGitHooks(repo, ["true"]);
		expect(written2).toEqual([]); // no rewrite

		const content = fs.readFileSync(path.join(repo, ".git", "hooks", "pre-commit"), "utf-8");
		expect(content.split("# generated by omp asset install-hooks")).toHaveLength(2); // header only once
	});

	test("preserves a user's own pre-commit hook", () => {
		const repo = makeRepo();
		fs.writeFileSync(path.join(repo, ".git", "hooks", "pre-commit"), "#!/bin/sh\necho user hook\n");
		installGitHooks(repo, ["true"]);

		const content = fs.readFileSync(path.join(repo, ".git", "hooks", "pre-commit"), "utf-8");
		expect(content).toContain("echo user hook");
		expect(content).toContain("# generated by omp asset install-hooks");
	});

	test("uninstall removes only hooks this tool wrote", () => {
		const repo = makeRepo();
		fs.writeFileSync(path.join(repo, ".git", "hooks", "pre-commit"), "#!/bin/sh\necho user hook\n");
		installGitHooks(repo, ["true"]);

		const removed = uninstallGitHooks(repo);
		expect(removed).toEqual(["pre-commit", "post-commit"]);

		// post-commit had no user prefix, so it is removed entirely.
		expect(fs.existsSync(path.join(repo, ".git", "hooks", "post-commit"))).toBe(false);
		// pre-commit keeps the user's own content, with the generated block stripped.
		const pre = fs.readFileSync(path.join(repo, ".git", "hooks", "pre-commit"), "utf-8");
		expect(pre).toContain("echo user hook");
		expect(pre).not.toContain("# generated by omp asset install-hooks");
	});
});
